package dao;
// Generated 8 mai 2024, 18:53:52 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

/**
 * Compte generated by hbm2java
 */
@Component
@Entity
@Table(name = "compte", schema = "public")
public class Compte implements java.io.Serializable {

	private int numero;
	private Utilisateur utilisateur;
	private int solde;
	private Date datecreation;
	private Set<Operation> operations = new HashSet<Operation>(0);

	public Compte() {
	}

	public Compte(int numero) {
		this.numero = numero;
	}

	public Compte(int numero, Utilisateur utilisateur, Integer solde, Date datecreation, Set<Operation> operations) {
		this.numero = numero;
		this.utilisateur = utilisateur;
		this.solde = solde;
		this.datecreation = datecreation;
		this.operations = operations;
	}
	public Compte(Utilisateur utilisateur, Integer solde, Date datecreation, Set<Operation> operations) {
		this.utilisateur = utilisateur;
		this.solde = solde;
		this.datecreation = datecreation;
		this.operations = operations;
	}

	@Id

	@Column(name = "numero", unique = true, nullable = false)
	@GeneratedValue
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iduser")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "solde")
	public Integer getSolde() {
		return this.solde;
	}

	public void setSolde(int solde) {
		this.solde = solde;
	}

	@Column(name = "datecreation", length = 254)
	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	public Set<Operation> getOperations() {
		return this.operations;
	}

	public void setOperations(Set<Operation> operations) {
		this.operations = operations;
	}

}
