package dao;
// Generated 8 mai 2024, 18:53:52 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

/**
 * Operation generated by hbm2java
 */
@Component

@Entity
@Table(name = "operation", schema = "public")
public class Operation implements java.io.Serializable {

	private int idoperation;
	private Compte compte;

	public Operation() {
	}

	public Operation(int idoperation) {
		this.idoperation = idoperation;
	}

	public Operation(int idoperation, Compte compte) {
		this.idoperation = idoperation;
		this.compte = compte;
	}

	@Id

	@Column(name = "idoperation", unique = true, nullable = false)
	@GeneratedValue

	public int getIdoperation() {
		return this.idoperation;
	}

	public void setIdoperation(int idoperation) {
		this.idoperation = idoperation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numero")
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

}
