package dao;
// Generated 8 mai 2024, 18:53:52 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

/**
 * Utilisateur generated by hbm2java
 */
@Component
@Entity
@Table(name = "utilisateur", schema = "public")
public class Utilisateur implements java.io.Serializable {

	private int iduser;
	private String nom;
	private String prenom;
	private String login;
	private String password;
	private Set<Compte> comptes = new HashSet<Compte>(0);

	public Utilisateur() {
	}

	public Utilisateur(int iduser) {
		this.iduser = iduser;
	}

	public Utilisateur(int iduser, String nom, String prenom, String login, String password, Set<Compte> comptes) {
		this.iduser = iduser;
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
		this.comptes = comptes;
	}
	public Utilisateur(String nom, String prenom, String login, String password, Set<Compte> comptes) {
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
		this.comptes = comptes;
	}

	@Id

	@Column(name = "iduser", unique = true, nullable = false)
	@GeneratedValue
	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "login", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Compte> getComptes() {
		return this.comptes;
	}

	public void setComptes(Set<Compte> comptes) {
		this.comptes = comptes;
	}

}
